### ISSUE TITLE
Bind address

### ISSUE THREAD

**Issue by LuKks** [mafintosh/bind-easy#1]
Allow cases like:
```js
const server = await bind.tcp(8080, '127.0.0.1')
// or at least:
const server = await bind.tcp(8080, { address: '127.0.0.1' })
```

Btw, I don't find it really necessary because I can actually create a server like always then `listen(port, address)` but I think it would be cool to have it in `bind-easy` for more use cases.

Feel free to close the issue.

**Comment by mafintosh** [comment]
PR welcome!

**Comment by LuKks** [comment]
#2
